version: '2'
services:
    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
          - oh_volume:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    php:
        build: ./_docker/php-fpm
        container_name: ov_php
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www/symfony:cached
        depends_on:
            - db
        links:
            - db
    node:
        image: "node:8"
        user: "node"
        links:
            - php
            - nginx
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
        volumes:
            - ./server:/home/node/app
        expose:
            - "80"
        command: "npm start"

    nginx:
        build: ./_docker/nginx
        ports:
            - "81:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./_docker/nginx/logs:/var/log/nginx:cached

volumes:
    oh_volume:
        external: true
