version: '2'
services:
    db:
        image: mysql:5.7
        container_name: oh_db
        ports:
            - "3306:3306"
        volumes:
          - oh_volume:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    php:
        build: ./_docker/php-fpm
        container_name: oh_php
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www/symfony:cached
        depends_on:
            - db
        links:
            - db
    node:
        build: ./_docker/node
        container_name: oh_node
        user: "node"
        tty: true
        links:
            - php
            - nginx
        environment:
            - NODE_ENV=production
        volumes:
            - ./:/home/node/app
        ports:
            - "80:3000"

    nginx:
        build: ./_docker/nginx
        container_name: oh_nginx
        ports:
            - "81:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./_docker/nginx/logs:/var/log/nginx:cached

volumes:
    oh_volume:
        external: true
